function TermsOfService() {
  return (
    <>
      <header>
        <h1>Terms of Service</h1>
        <p>
          By using Silver Agent, you agree to the following terms and
          conditions:
        </p>
      </header>
      <article>
        <section>
          <h2>AI Disclaimer</h2>
          <p>
            Responses generated by Silver Agent are produced by artificial
            intelligence and may contain inaccuracies. Users should verify
            information with a licensed Medicare insurance professional.
          </p>
        </section>
        <section>
          <h2>No Insurance Advice</h2>
          <p>
            Silver Agent does not provide insurance advice, plan
            recommendations, or enrollment services.
          </p>
        </section>
        <section>
          <h2>Acceptable Use</h2>
          <p>
            Users may not:
            <ul>
              <li>attempt to exploit or manipulate the AI system</li>
              <li>submit malicious code</li>
              <li>attempt unauthorized access</li>
              <li>use the system for unlawful purposes</li>
            </ul>
          </p>
        </section>
        <section>
          <h2>Limitation of Liability</h2>
          <p>
            Silver Agent shall not be liable for decisions made based on
            AI-generated responses.
          </p>
        </section>
        <section>
          <h2>Governing Law</h2>
          <p>Arizona.</p>
        </section>
      </article>
    </>
  );
}

export default TermsOfService;
